Remove support for PhantomJS
arquillian/arquillian-extension-drone pull request #403
Opened 2023-08-08 10:08 UTC by mabartos

Closes #402

Removal of all workarounds, components, and integrations related to the PhantomJS.

2023-09-11 09:39 UTC, mabartos commented
@bartoszmajsak Can you check it, please?

2023-09-13 08:50 UTC, bartoszmajsak requested changes
Thanks for taking care of it @mabartos! I think we have to bring back one test which was deleted by "accident" and we should be good.

2023-09-13 08:50 UTC, bartoszmajsak commented on drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceLatestReleaseFromTagsTestCase.java
I don't think this test should be removed simply because it's using PhantomJS as a repository "under test". Also, notice that the entire interaction is stubbed using hoverfly so in fact it does not even reach the actual GitHub server. I think we should simply bring it back and perhaps comment that it's stubbed repo as it's clearly not obvious based on what happened here :)

2023-09-25 09:24 UTC, mabartos commented on drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceLatestReleaseFromTagsTestCase.java
Aaah, you're definitely right :) I'll do it

2023-10-02 15:39 UTC, mabartos commented
@bartoszmajsak I couldn't execute the `GithubSourceLatest*` tests on my local machine.

2023-10-05 11:05 UTC, mabartos commented
@bartoszmajsak Can you please review the PR again? Thanks

2023-10-10 09:49 UTC, mabartos commented
The `GithubSourceLatest*` tests passed.

2024-03-31 00:46 UTC, closed without merging